# Generated by Django 4.2.3 on 2025-03-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
